apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  annotations:
    cloudprovider.harvesterhci.io/ipam: dhcp
  labels:
    app: {{ .Values.appName }}
spec:
  ports:
  - name: gopherport
    port: {{ .Values.lbport }}
    protocol: TCP
    targetPort: {{ .Values.containerport }}
    nodePort: {{ .Values.nodeport }}
  selector:
    app: {{ .Values.appName }}
    tier: gopherhole
  type: LoadBalancer